### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by hijiangtao** [hijiangtao/billboard-generator#1]
* [x] Angular 组件与服务抽象 https://github.com/hijiangtao/billboard-generator/commit/7cc28caf2e1606d0af0e56faddca5e6da5b851fc
* [x] Ant Design 设计替换 https://github.com/hijiangtao/billboard-generator/commit/23ae24b186271322a361a18583f95e79cd15552a
* [x] 支持用户自定义图片上传与主题色提取 https://github.com/hijiangtao/billboard-generator/commit/e9bff2190a081b6ad1eed89a53418d8c3c8bfdf8
* [x] 支持根据背景色深浅自动调节文字颜色~推荐配色并允许用户替换文字填色~ https://github.com/hijiangtao/billboard-generator/commit/af1793044a158506ffe81f1d8a4953cb9391ea1a

**Comment by hijiangtao** [comment]
Done
